[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_version = "18"

[functions.create-payment-intent]
  memory_size = 1024
  timeout = 10

[functions.create-stripe-account]
  memory_size = 1024
  timeout = 10

[functions.stripe-account-status]
  memory_size = 1024
  timeout = 10
